plugins {
    id 'java'
}

group = 'com.suraev'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    springVersion = '3.4.4'
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter:${springVersion}"
    implementation "org.springframework.boot:spring-boot-starter-web:${springVersion}"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springVersion}"
    implementation 'org.liquibase:liquibase-core:4.31.1'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springVersion}"
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:4.0.0-M1'
    testImplementation 'org.mockito:mockito-core:2.1.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.16.1'

    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    compileOnly 'org.projectlombok:lombok:1.18.36'
}

test {
    useJUnitPlatform()
}