server:
  port: 0
  servlet:
    context-path: /api/v1/

spring:
    application:
      name: order-service

    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update

    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

discount:
  service:
    url: http://discount-service

rabbitmq:
    excName: orderCreate
    qName: message.queue
    queue_with_auto_ack: queue_with_auto_ack
    queue_without_auto_ack: queue_without_auto_ack

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: order-service

